apiVersion: v1
kind: Service
metadata: 
  name: jenkinservice 
spec:
  type: ClusterIP 
  ports: 
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector: 
    app: myapp

