apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        env: dev
      containers:
        - image: jenkins/jenkins:lts
          name: jenkins
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          hostPath: 
            path: /root/jenkins_data
            type: Directory
