apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:2.60.2
          name: jenkins
      nodeSelector:
        env: dev
