apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: jenkinslb
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: myapp
