apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-cpu-quota
  namespace: myenv
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: 3
